// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

package com.mycompany.helloworld;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class HelloWorld {
    public abstract String getMsg();

    public abstract void setMsg(String msg);

    public static native HelloWorld create();

    private static final class CppProxy extends HelloWorld
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String getMsg()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getMsg(this.nativeRef);
        }
        private native String native_getMsg(long _nativeRef);

        @Override
        public void setMsg(String msg)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setMsg(this.nativeRef, msg);
        }
        private native void native_setMsg(long _nativeRef, String msg);
    }
}
